
cypher = ("ZCFGASACFWOZGDCFHQIZZWGGCJSFFWRRSBCPGSFJOBHASFFWHHGSBNMASGAMZOFGUIWRSGYWBYWSFFSGSFJWGHRSBHWBUORCFBASBHGRSJOBOUOFWGOZZWSRCTTSBRGQSOIGSGQIUCRROASRDFSTSQHIFSKSWFRBSGGVOFRPOQYGAWGQVWSJCIGGHOHSROQFILOPGHOWBSFVOGHSBSRFODOQWHMGGOQVSAGIPQCBHFOQHGGCIHVSFBSFGIBVODDWZMWBHFWUIWBUAWODZOQWRIGDIZGSGQVIPSFHGTFSOYWSFPWGAOFYGGITTWLGGDSOYSOGWSGXOBWGGOFMGAWZZOMQOHVOFGSGMSBWGSWPIHHCBWBHFOBSHTZCKSFWSGHCIHZOKAOVOFOBSSPZ")
# message = "HELLO"
alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
# key = 7
encrypt = ''
decrypt = ''

# message = input('enter the message: ').upper()

print ("Original: " + cypher)
# for i in message:
#      position = alphabet.find(i)
#      new_position = (position+key) % 26
#      encrypt += alphabet[new_position]
# print("Encrypted: " + encrypt)
key = 0
# for i in cypher:
#     pos = alphabet.find(i)
#     new_pos = (pos-key) % 26
#     decrypt += alphabet[new_pos]
# print(cypher)
# print(decrypt)

while key != 26:
    for i in cypher:
        pos = alphabet.find(i)
        new_pos = (pos - key) % 26
        decrypt += alphabet[new_pos]
    print("Key " + str(key) + ": " + decrypt)
    decrypt = ''
    key += 1

answer = "LORSMEMORIALSPORTCULLISSOVERRIDDENOBSERVANTMERRITTSENZYMESMYLARSGUIDESKINKIERRESERVISTDENTINGADORNMENTSDEVANAGARISALLIEDOFFENDSCEAUSESCUGODDAMEDPREFECTUREWEIRDNESSHARDBACKSMISCHIEVOUSSTATEDACRUXABSTAINERHASTENEDRAPACITYSSACHEMSUBCONTRACTSSOUTHERNERSUNHAPPILYINTRIGUINGMIAPLACIDUSPULSESCHUBERTSFREAKIERBISMARKSSUFFIXSSPEAKEASIESJANISSARYSMILLAYCATHARSESYENISEIBUTTONINTRANETFLOWERIESTOUTLAWMAHARANEEBL"
outF = open("test.txt", "w")
# write line to output file
outF.write(answer)
outF.close()
